UI Redesign
amikha1lov/RecApp pull request #66
Opened 2021-01-30 11:09 UTC by SeaDve

It is still not perfect, but most of the features now work.

(I'll update this PR with those features not working later)

![image](https://user-images.githubusercontent.com/64297935/106354676-8242e680-632e-11eb-824b-6a964b46041e.png)

2021-01-30 14:54 UTC, amikha1lov commented
it's looks nice, but we should follow GNOME HIG in preferences window

2021-01-30 19:12 UTC, amikha1lov requested changes

2021-01-30 19:12 UTC, amikha1lov commented on src/window.ui
> +                  <object class="GtkButton" id="_record_button">
https://gitlab.com/Latesil/folder-cleaner/-/blob/dev/foldercleaner/user_folder.ui#L29 
<style>
    <class name="suggested-action"/>
</style>

2021-01-31 00:30 UTC, SeaDve commented on src/window.py
> +        #_record_button {
fixed it. TIL. Is there some documentation about these style classes?

2021-01-31 00:39 UTC, SeaDve commented
Oh shoot, I messed it up. I put it in the wrong folder.

2021-01-31 00:59 UTC, SeaDve commented
Ughh, sorry! I think I'll just make a new PR.

2021-01-31 00:59 UTC, closed without merging